### ISSUE TITLE
core-js下的fn类库没有提交

### ISSUE THREAD

**Issue by hevily** [xtTech/dc-sdk-js#1]
require('core-js/fn/object/define-property')
require('core-js/fn/object/create')
require('core-js/fn/object/assign')
require('core-js/fn/array/for-each')
require('core-js/fn/array/index-of')
require('core-js/fn/array/map')
require('core-js/fn/function/bind')
require('core-js/fn/promise')

**Comment by drafish** [comment]
是我没有把core-js加到依赖项里，现在已经更新代码了，你再试下

**Comment by hevily** [comment]
![image](https://user-images.githubusercontent.com/644260/55847754-17368780-5b7d-11e9-8cb3-1f1c3f0c173b.png)
好像不是fn 应该是es 不知道是不是版本号不对

**Comment by drafish** [comment]
是版本号的问题，你的core-js应该是3版本的，我原来引的是2版本的。3版本应该引features目录下的文件，把我原来的fn都换成features就可以了。

**Comment by hevily** [comment]
恩 
有一个新的问题就是通过编译发现ie8 下面还是有不识别的关键字 
![image](https://user-images.githubusercontent.com/644260/55848545-de4be200-5b7f-11e9-9e26-c43e02d4d46c.png)

![image](https://user-images.githubusercontent.com/644260/55848524-d12ef300-5b7f-11e9-8d8b-0f6b9c15c80b.png)

webpack.config配置
![image](https://user-images.githubusercontent.com/644260/55848585-03405500-5b80-11e9-8d10-fe06410a9b92.png)

![image](https://user-images.githubusercontent.com/644260/55848567-f459a280-5b7f-11e9-935c-582a92a76272.png)

**Comment by drafish** [comment]
这是因为UglifyJS没有转译第三方库中的catch，我试着在业务代码中写catch可以正常转译
```js
let obj = { catch: '111' }
console.log(obj.catch)
try {
  console.log(obj.c.a)
} catch (error) {
  console.log(error)
}
let foo = new Promise((resolve, reject) => {
  // setTimeout(() => {
  //   resolve('resolve result')
  // })
  setTimeout(() => {
    reject('reject error')
  })
});

foo.then(result => {
  console.log(result)
}).catch(error=> {
  console.log(error)
})
```
